export type Testimonial = { name: string; location: string; quote: string };

export const testimonials: Testimonial[] = [
  { name: "Ricardo Mendes", location: "São Paulo - SP", quote: "Processo extremamente profissional. A mediação estratégica garantiu que a venda da minha empresa ocorresse sob total sigilo e valor justo." },
  { name: "Amanda Schutz", location: "Blumenau - SC", quote: "Excelente atendimento. O formato transparente me deu a segurança que eu precisava para investir no meu primeiro consórcio de alto padrão." },
  { name: "Carlos Eduardo Lima", location: "Goiânia - GO", quote: "Superou minhas expectativas. A equipe filtrou exatamente o público comprador correto, poupando meu tempo e fechando o negócio com maestria." },
  { name: "Mariana Fontes", location: "Rio de Janeiro - RJ", quote: "A atenção aos detalhes e o suporte jurídico durante a transição da minha empresa foram impecáveis. Recomendo de olhos fechados." },
  { name: "Roberto Alencar", location: "Recife - PE", quote: "O atendimento executivo é o grande diferencial. Fui tratado com muita exclusividade desde a primeira reunião até a assinatura do contrato." },
  { name: "Fernanda Prates", location: "Porto Alegre - RS", quote: "Consegui expandir minha frota através do consórcio planejado por eles. Economia real e parcelas que couberam perfeitamente no fluxo de caixa." },
  { name: "Marcos Vinícius", location: "Belo Horizonte - MG", quote: "Discrição e eficiência definem. Vender uma operação em funcionamento é complexo, mas a assessoria deles tornou tudo muito simples." },
  { name: "Juliana Carvalho", location: "Brasília - DF", quote: "Equipe extremamente preparada. O mapeamento de mercado que fizeram para avaliar meu negócio foi cirúrgico e muito realista." },
  { name: "Tiago Castelo", location: "Belém - PA", quote: "Um atendimento focado em soluções. A flexibilidade e a clareza nas explicações sobre as cotas me fizeram fechar o negócio na hora." },
  { name: "Letícia Albuquerque", location: "Curitiba - PR", quote: "O pós-venda deles é excelente. Mesmo após a conclusão da intermediação, continuaram prestando todo o suporte necessário." },
  { name: "Bruno Cavalcanti", location: "Salvador - BA", quote: "Transação rápida, segura e sem burocracia desnecessária. Focaram no que realmente importava para fechar a venda da minha distribuidora." },
  { name: "Camila Negrão", location: "Cuiabá - MT", quote: "Investimento seguro. A equipe desenhou uma estratégia de lances para o consórcio que deu certo muito antes do que eu esperava." },
  { name: "Rodrigo Fonseca", location: "Vitória - ES", quote: "Fiquei impressionado com o nível dos compradores que trouxeram para a mesa de negociação. Público altamente qualificado." },
  { name: "Patrícia Guedes", location: "Manaus - AM", quote: "A abordagem executiva e o posicionamento de mercado deles fazem toda a diferença para quem busca transações de alto valor." },
  { name: "Gustavo Morais", location: "Natal - RN", quote: "Pontuais, profissionais e honestos. Não prometem o impossível, mas entregam o melhor resultado viável com muita agilidade." },
  { name: "Vanessa Toledo", location: "Campinas - SP", quote: "Se você busca um atendimento que entende as dores de um empresário, encontrou. Me senti apoiada durante todo o processo de valuation." },
  { name: "André Junqueira", location: "Uberlândia - MG", quote: "Transparência total em relação às taxas e prazos do consórcio. Sem surpresas na hora da contemplação. Nota 10." },
  { name: "Beatriz Viana", location: "Florianópolis - SC", quote: "Conseguiram alinhar perfeitamente as expectativas entre comprador e vendedor. Uma mediação impecável e muito pacífica." },
  { name: "Marcelo Rocha", location: "Fortaleza - CE", quote: "A estrutura do atendimento remoto deles funciona tão bem que parecia que estavam na sala ao lado. Processo muito fluido." },
  { name: "Elaine Silveira", location: "Campo Grande - MS", quote: "Recomendo para qualquer empresário que queira vender seu legado com a certeza de que ele será entregue em boas mãos." },
  { name: "Sérgio Antunes", location: "Campina Grande - PB", quote: "Investimento estratégico com retorno claro. A equipe foi impecável na apresentação de cenários para o meu consórcio de imóveis comerciais." },
  { name: "Natália Meireles", location: "Santos - SP", quote: "A avaliação inicial da minha empresa foi muito realista. Isso evitou desgastes e atraiu investidores prontos para fechar a transação." },
  { name: "Arthur Rezende", location: "Londrina - PR", quote: "Muito satisfeito com a postura transparente nas reuniões de negociação. Segurança completa do início ao fim do processo de venda." },
  { name: "Tatiana Barbosa", location: "Caxias do Sul - RS", quote: "Excelente suporte na estruturação de cotas para expansão de frotas pesadas. Atendimento executivo diferenciado focado em resultados." },
  { name: "Felipe Nogueira", location: "Uberaba - MG", quote: "Condução perfeita no processo de transição da minha indústria. Sigilo absoluto garantido por profissionais de alto nível de mercado." },
  { name: "Priscila Barros", location: "Niterói - RJ", quote: "Um consórcio planejado com inteligência e lances estratégicos. Consegui a contemplação no prazo que a minha empresa precisava." },
  { name: "Gabriel Fontoura", location: "Anápolis - GO", quote: "Dinamismo e mediação justa. Sentamos à mesa com compradores qualificados e o acordo foi fechado em tempo recorde com tranquilidade." },
  { name: "Letícia Fagundes", location: "Joinville - SC", quote: "Toda a documentação foi organizada de forma impecável. Facilitou muito a auditoria dos compradores e acelerou o fechamento da venda." },
  { name: "Maurício Villela", location: "Caruaru - PE", quote: "Atendimento remoto eficiente e muito próximo. As cotas apresentadas preencheram perfeitamente as necessidades do nosso plano de investimento." },
  { name: "Sabina Coimbra", location: "Feira de Santana - BA", quote: "A consultoria demonstrou profundo conhecimento de mercado corporativo. Consegui vender meu comércio com valorização justa e sem estresse." },
  { name: "Renato Linhares", location: "Viamão - RS", quote: "O modelo de consórcio imobiliário que me apresentaram foi excelente para proteger o capital da empresa contra a inflação." },
  { name: "Débora Vasconcelos", location: "Jundiaí - SP", quote: "Equipe que sabe como valorizar o ativo de um fundador. O suporte jurídico e comercial foi essencial para blindar a transação." },
  { name: "Leonardo Paim", location: "Maringá - PR", quote: "Negócios de alto padrão exigem profissionais desse nível. A assessoria me trouxe investidores reais e evitou curiosos na plataforma." },
  { name: "Giovana Lemos", location: "Juiz de Fora - MG", quote: "A consultoria de lances foi certeira. O planejamento de longo prazo se pagou muito antes do previsto na contemplação da cota." },
  { name: "Alexandre Frota", location: "Macaé - RJ", quote: "Ótima experiência na venda da minha empresa de serviços. O processo fluiu com total discrição entre os parceiros e mercado." },
  { name: "Mônica Sales", location: "Petrolina - PE", quote: "Fiquei surpreendido com o profissionalismo desde o primeiro contato. O atendimento executivo atendeu perfeitamente ao meu perfil investidor." },
  { name: "Vinícius Prestes", location: "Passo Fundo - RS", quote: "Soluções sob medida para investimentos de grande porte. A clareza nas informações contratuais me trouxe muita paz de espírito." },
  { name: "Clarice Magalhães", location: "Ribeirão Preto - SP", quote: "A equipe conseguiu conduzir uma transição suave para os meus funcionários e novos proprietários durante a venda do fundo." },
  { name: "Rogério Diniz", location: "Cascavel - PR", quote: "Encontrei segurança e rentabilidade planejada no consórcio comercial deles. Suporte técnico qualificado em todas as etapas de lances." },
  { name: "Bianca Azevedo", location: "Ipatinga - MG", quote: "Recomendo pela seriedade e capacidade de entrega. Conseguiram unir as pontas idealmente na negociação da minha rede de lojas." },
  { name: "Douglas Camargo", location: "Nova Friburgo - RJ", quote: "Atendimento objetivo e transparente focado nas metas do cliente. Consegui alinhar a venda do meu negócio de forma limpa." },
  { name: "Helena Dornelles", location: "Pelotas - RS", quote: "Muito satisfeita com a análise financeira inicial. Ela deu a base sólida para apresentar o negócio ao mercado com segurança." },
  { name: "Samuel Viana", location: "Sorocaba - SP", quote: "O formato do consórcio foi uma ótima ferramenta para o nosso plano de expansão patrimonial. Sem taxas abusivas ou burocracia." },
  { name: "Miriam Cordeiro", location: "Foz do Iguaçu - PR", quote: "Mediação executiva espetacular. Resolveram todos os impasses comerciais com maestria e garantiram a assinatura do contrato final." },
  { name: "Luciano Pires", location: "Montes Claros - MG", quote: "A melhor opção para quem busca vender ativos de valor sob total sigilo de mercado. Atendimento diferenciado e exclusivo." },
  { name: "Carolina Siqueira", location: "Petrópolis - RJ", quote: "Excelente alternativa financeira. A estratégia desenhada pela equipe funcionou perfeitamente para a aquisição da nova sede própria." },
  { name: "Diogo Arruda", location: "Santa Maria - RS", quote: "Agilidade e competência marcaram o processo de venda. Os investidores trazidos pela empresa eram exatamente o perfil buscado." },
  { name: "Giselle Ramos", location: "Piracicaba - SP", quote: "Muito bem impressionada com a organização burocrática e estrutural da intermediação. Nada foi deixado ao acaso na operação." },
  { name: "Otávio Marcondes", location: "Ponta Grossa - PR", quote: "Planejamento financeiro eficiente através de cotas bem estruturadas. Recomendo para investidores que prezam por liquidez e prazos reais." },
  { name: "Flávia Quintana", location: "Sete Lagoas - MG", quote: "A equipe conduziu as rodadas de investimento com extrema elegância e capacidade técnica. Venda realizada com sucesso absoluto." },
  { name: "Henrique Ortega", location: "Volta Redonda - RJ", quote: "Um trabalho sério que gera confiança mútua. A venda da nossa distribuidora foi tratada com a devida importância corporativa." },
  { name: "Roberta Lunardi", location: "Rio Grande - RS", quote: "Consegui diversificar meus ativos imobiliários com as soluções estruturadas que me ofereceram. Ótimo atendimento do início ao fim." },
  { name: "Murilo Aguiar", location: "Bauru - SP", quote: "Foco em resultados de alto valor. O processo de filtragem dos interessados poupou semanas de reuniões improdutivas para nós." },
  { name: "Isadora Castilho", location: "Guarapuava - PR", quote: "A condução do valuation foi transparente e detalhada. Permitiu defender o valor justo do meu negócio perante a banca compradora." },
  { name: "Wagner Peixoto", location: "Divinópolis - MG", quote: "Conforto e clareza em todas as etapas contratuais do consórcio pesado. Suporte especializado que faz a diferença no mercado atual." },
  { name: "Patrícia Villas", location: "Campos dos Goytacazes - RJ", quote: "O profissionalismo demonstrado superou em muito as corretoras convencionais. Foco total em grandes transações de empresas." },
  { name: "Fabrício Telles", location: "São Leopoldo - RS", quote: "Excelente retorno sobre o tempo investido. A transação ocorreu dentro dos prazos estipulados e com conformidade jurídica total." },
  { name: "Simone Albuquerque", location: "São José dos Campos - SP", quote: "O consórcio empresarial deles se tornou a principal ferramenta de modernização do nosso parque fabril. Processo excelente." },
  { name: "Daniel Mello", location: "Toledo - PR", quote: "A postura da assessoria durante os momentos tensos da negociação foi fundamental para manter o negócio de pé até o final." },
  { name: "Aline Godoy", location: "Governador Valadares - MG", quote: "Transmissão de total credibilidade. Consegui repassar minha franquia para um operador qualificado e com as garantias necessárias." },
  { name: "Leandro Mussi", location: "Araraquara - SP", quote: "Análise cirúrgica das condições de mercado para posicionar nossa empresa na venda. Sucesso alcançado graças a essa estratégia básica." },
  { name: "Camila Dornas", location: "Betim - MG", quote: "O consórcio estruturado ajudou a blindar nosso fluxo de caixa enquanto planejamos a expansão física da rede de lojas." },
  { name: "Anderson Goulart", location: "Novo Hamburgo - RS", quote: "Discrição total era minha exigência número um por questões de concorrência. Eles cumpriram à risca todo o protocolo acordado." },
  { name: "Elaine Portela", location: "Paranaguá - PR", quote: "A avaliação transparente do fundo de comércio deu muita robustez à proposta de venda enviada aos fundos parceiros." },
  { name: "Valter Sanches", location: "São Carlos - SP", quote: "Perfil executivo de alto nível. Conversar com quem realmente entende de fusões e aquisições facilitou muito a jornada de venda." },
  { name: "Lilian Fraga", location: "Santa Luzia - MG", quote: "Excelente ferramenta de alavancagem para compra de máquinas industriais. O consórcio personalizado trouxe grande economia tributária." },
  { name: "Marcos Scherer", location: "Santa Cruz do Sul - RS", quote: "Negócio fechado com agilidade e valorização real do capital investido na criação da marca. Suporte indispensável." },
  { name: "Regina Scalco", location: "Arapongas - PR", quote: "Processo claro e limpo em todas as esferas. A apresentação executiva da nossa empresa aos investidores ficou impecável." },
  { name: "Christian Nóbrega", location: "Franca - SP", quote: "Uma parceria de longo prazo baseada em resultados concretos e honestidade comercial absoluta. Recomendo os serviços sempre." },
  { name: "Viviane Dutra", location: "Ribeirão das Neves - MG", quote: "A equipe desenhou um cenário realista de lances embutidos no consórcio. A estratégia se pagou rapidamente no primeiro ano." },
  { name: "André Guedes", location: "Bento Gonçalves - RS", quote: "O repasse do controle societário da minha empresa familiar foi feito de forma diplomática e com total segurança jurídica." },
  { name: "Júlia Brandão", location: "Pinhais - PR", quote: "Equipe muito atenciosa e focada no perfil ideal de comprador institucional. Economia de tempo absurda nas rodadas de conversa." },
  { name: "Raul Fagundes", location: "Limeira - SP", quote: "O modelo executivo de gestão de contratos deles nos deu muita tranquilidade durante a venda de nossos ativos imobiliários." },
  { name: "Carla Mattos", location: "Poços de Caldas - MG", quote: "Planejamento sob medida para empresas de médio porte que buscam frotas novas sem recorrer a financiamentos bancários abusivos." },
  { name: "Roberto Kroeff", location: "Erechim - RS", quote: "A assessoria na venda do nosso grupo industrial foi precisa e eficiente. Resultado final muito satisfatório para ambas as partes." },
  { name: "Sofia Valente", location: "Colombo - PR", quote: "Transparência e agilidade definem o trabalho. A negociação correu muito bem estruturada por dados reais de mercado." },
  { name: "César Marinho", location: "Taubaté - SP", quote: "Fiquei impressionado com a qualidade do material preparado para a divulgação restrita da nossa carteira de clientes." },
  { name: "Marta Sales", location: "Patos de Minas - MG", quote: "Conseguimos atingir nossos objetivos patrimoniais utilizando as cotas de consórcio planejadas para o nosso perfil executivo." },
  { name: "Nelson Dornelles", location: "Uruguaiana - RS", quote: "Negociação direta com tomadores de decisão reais. Eliminação de intermediários desqualificados agilizou o processo de venda." },
  { name: "Angélica Neves", location: "Cambé - PR", quote: "O processo corporativo de valuation deles deu o tom profissional necessário para atrair grandes compradores nacionais." },
  { name: "Rodrigo Simões", location: "Americana - SP", quote: "Solução perfeita para investimentos de longo prazo em infraestrutura. Suporte completo desde a análise inicial até a contemplação." },
  { name: "Telma Rezende", location: "Teófilo Otoni - MG", quote: "A venda da operação da minha rede comercial ocorreu com o sigilo desejado e de acordo com as diretrizes acordadas." },
  { name: "Paulo Backes", location: "Bagé - RS", quote: "Profissionais preparados para lidar com estruturas societárias complexas. A mediação garantiu um desfecho ótimo para o grupo." },
  { name: "Sandra Lins", location: "Campo Largo - PR", quote: "Encontrei segurança técnica e comercial na montagem da nossa carteira de consórcio de galpões logísticos." },
  { name: "Emerson Goulart", location: "Marília - SP", quote: "Abordagem muito assertiva no mercado de fusões e aquisições. Excelente carteira de investidores nacionais e internacionais." },
  { name: "Tânia Mendes", location: "Pouso Alegre - MG", quote: "Excelente acompanhamento burocrático e comercial. O repasse da minha marca foi realizado sem sobressaltos e de forma pacífica." },
  { name: "Jorge Schein", location: "Ijuí - RS", quote: "A experiência acumulada da equipe trouxe soluções rápidas para os entraves que surgiram na auditoria final de compra." },
  { name: "Gisele Bueno", location: "Piraquara - PR", quote: "A melhor estratégia financeira para expansão planejada de imóveis institucionais sem depender de linhas tradicionais de crédito." },
  { name: "Cláudio Prates", location: "São Carlos - SP", quote: "A avaliação da empresa se mostrou precisa no momento das propostas reais recebidas. Conhecimento amplo do mercado executivo." },
  { name: "Vanessa Borges", location: "Barbacena - MG", quote: "Condução de alto nível corporativo na intermediação da venda do nosso negócio tradicional familiar. Recomendo o trabalho." },
  { name: "Hugo Sperb", location: "Santa Rosa - RS", quote: "Rapidez no retorno das consultas e total transparência sobre as possibilidades reais de venda da nossa planta industrial." },
  { name: "Miriam Castro", location: "Fazenda Rio Grande - PR", quote: "O plano de lances desenhado para o consórcio corporativo reduziu drasticamente o custo final de capital da nossa empresa." },
  { name: "Eduardo Maluf", location: "Presidente Prudente - SP", quote: "Atendimento exclusivo focado em quem não tem tempo a perder com especuladores. Investidores trazidos eram qualificados." },
  { name: "Priscila Costa", location: "Sabará - MG", quote: "A equipe tratou a venda da nossa empresa com muito respeito ao legado construído. Integridade e competência do início ao fim." },
  { name: "Luís Henrique Fleck", location: "Lajeado - RS", quote: "Resolutividade e clareza jurídica na redação do acordo de confidencialidade e na proposta definitiva de fechamento do negócio." },
  { name: "Mônica Penteado", location: "Castro - PR", quote: "Conseguimos planejar nossos investimentos em novos ativos logísticos com total previsibilidade orçamentária e suporte técnico." },
  { name: "Gustavo Barreto", location: "Indaiatuba - SP", quote: "A apresentação profissional da nossa empresa ao mercado estratégico foi o fator determinante para atrair propostas firmes." },
  { name: "Silvana Antunes", location: "Vespasiano - MG", quote: "Excelente formato de atendimento corporativo focado na resolução de conflitos entre as partes. Muito profissionalismo." },
  { name: "Mauro Stumpf", location: "Farroupilha - RS", quote: "O processo de venda transcorreu de forma organizada e dentro da legalidade esperada para operações dessa magnitude comercial." },
  { name: "Natália Silveira", location: "Francisco Beltrão - PR", quote: "A assessoria na análise de viabilidade das cotas corporativas foi fundamental para a tomada de decisão segura da nossa diretoria." },
];
